layout_spectrum: 0.3195938
color:
  saturation: 0
  brandStrength: 0.6015531
  lightness: 1
  brandColors:
    - '#F0EBE7'
    - '#F4CEB4'
    - '#CF9276'
    - '#391F15'
    - '#A3664A'
  rhythmicContrast: 0
typography_spectrum: 0.3948626
name: Grant Luckey
